const { Agency, AgencySchema } = require('./agencyModel')
const { User, UserSchema } = require('./userModel')
const { RegimenFiscal, RegimenFiscalSchema} = require('./regFiscalModel')
const { Clasificacion, ClasificacionSchema } = require('./clasificacionModel')
const { Document, DocumentSchema } = require('./documentModel')
const { Ciudad, CiudadSchema} = require('./ciudadModel')
const { ResponsabilidadFiscal, ResponsabilidadFiscalSchema} = require('./responsabilidadFiscalModel')
const { Cliente, ClienteSchema } =require('./clienteModel')
const { Departamento,DepartamentoSchema } = require('./departamentoModel')
const { Detalle,DetalleSchema } = require('./detalleModel')
const { Precio, PrecioSchema} = require('./preciosModel')
const { Proveedor, ProveedorSchema} = require('./proveedoresModel')
const { ActividadEconomica,ActividadEconomicaSchema } = require('./actividadModel')
const { Bitacora,BitacoraSchema } = require('./bitacoraModel')

function setupModels(sequelize) {
  Precio.init(PrecioSchema,Precio.config(sequelize))
  Proveedor.init(ProveedorSchema,Proveedor.config(sequelize))
  Detalle.init(DetalleSchema,Detalle.config(sequelize))
  RegimenFiscal.init(RegimenFiscalSchema,RegimenFiscal.config(sequelize))
  Departamento.init(DepartamentoSchema, Departamento.config(sequelize))
  User.init(UserSchema, User.config(sequelize))
  Bitacora.init(BitacoraSchema, Bitacora.config(sequelize))
  Agency.init(AgencySchema,Agency.config(sequelize))
  Clasificacion.init(ClasificacionSchema,Clasificacion.config(sequelize))
  Document.init(DocumentSchema,Document.config(sequelize))
  Ciudad.init(CiudadSchema,Ciudad.config(sequelize))
  ResponsabilidadFiscal.init(ResponsabilidadFiscalSchema,ResponsabilidadFiscal.config(sequelize))
  Cliente.init(ClienteSchema,Cliente.config(sequelize))
  ActividadEconomica.init(ActividadEconomicaSchema,ActividadEconomica.config(sequelize))


  Bitacora.associate(sequelize.models)
  User.associate(sequelize.models)
  Precio.associate(sequelize.models)
  Proveedor.associate(sequelize.models)
  ActividadEconomica.associate(sequelize.models)
  Detalle.associate(sequelize.models)
  RegimenFiscal.associate(sequelize.models)
  Departamento.associate(sequelize.models)
  Agency.associate(sequelize.models)
  Clasificacion.associate(sequelize.models)
  Document.associate(sequelize.models)
  Ciudad.associate(sequelize.models)
  ResponsabilidadFiscal.associate(sequelize.models)
  Cliente.associate(sequelize.models)
}
module.exports = setupModels